Update Instalation.rst
Numpy needs to be installed first as it's required to install pandas

........
Collecting pandas>=0.15.2 (from seaborn)
  Downloading https://files.pythonhosted.org/packages/d2/1b/dd36a304c9e78b64abf828d261f2e62e1be2447bc3bc06ccad5250265b27/pandas-0.24.0.tar.gz (11.8MB)
    100% |████████████████████████████████| 11.8MB 984kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xYsbi1/pandas/setup.py", line 732, in <module>
        ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
      File "/tmp/pip-install-xYsbi1/pandas/setup.py", line 475, in maybe_cythonize
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
      File "/hpc-home/ethering/hyde/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1160, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
      File "/hpc-home/ethering/hyde/lib/python2.7/site-packages/pkg_resources/__init__.py", line 435, in get_provider
        __import__(moduleOrReq)
    ImportError: No module named numpy